# -*- coding: utf-8 -*-
"""summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GB6jILVND0Zme-Rw7MuUVubTiQ1qcbkM
"""

!pip install openai python-dotenv
!pip install gradio
!pip install openai==0.28

from dotenv import load_dotenv
import os

# Load .env file
load_dotenv(dotenv_path='/content/drive/MyDrive/github_projects/text_summarizer/.env')
API_KEY = os.getenv("OPENAI_API_KEY")

# Confirm that the API key has been loaded (print statement for testing)
print("API Key loaded:", bool(API_KEY))

import openai
openai.api_key = API_KEY

def summarize_text(text):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # Change to a supported model
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": f"Summarize the following text:\n\n{text}"}
        ],
        max_tokens=150,  # Adjust based on desired summary length
        temperature=0.5,
    )
    summary = response['choices'][0]['message']['content'].strip()
    return summary

import gradio as gr

gr.Interface(fn=summarize_text, inputs="text", outputs="text", title="Text Summarizer").launch()

# Sample text for summarization
text = """
Artificial Intelligence is a rapidly growing field with numerous applications in various domains. From healthcare to finance, AI is changing how industries operate by providing more efficient solutions, improving accuracy, and enabling new possibilities for innovation. As AI continues to advance, ethical considerations and the need for regulatory frameworks have become increasingly important.
"""

# Generate the summary
summary = summarize_text(text)
print("Original Text:", text)
print("\nSummary:", summary)

!pip freeze > /content/drive/MyDrive/github_projects/text_summarizer/requirements.txt